site_name: Your Documentation
site_url: http://doc.kaboli.xyz/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide: user-guide.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true